Calendar/Controllers/NovemberController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Calendar.Models;
using Microsoft.Extensions.Localization;

namespace Calendar.Controllers
{
    public class NovemberController : Controller
    {
        private readonly IStringLocalizer<NovemberController> _localizer;

        public NovemberController(IStringLocalizer<NovemberController> localizer)
        {
            _localizer = localizer;
        }

        public IActionResult Index(int date)
        {
            ViewData["Url"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}{this.Request.Path}{this.Request.QueryString}";

            if (date > 0)
            {
                ViewData["BaseUrl"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}/{this.Request.Path.ToString().Split('/')[1]}/{this.ControllerContext.RouteData.Values["controller"].ToString()}";
                ViewData["Title"] = _localizer[$"{date}title"];
                ViewData["Description"] = _localizer[$"{date}description"];
                ViewData["Image"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}/{this.Request.Path.ToString().Split('/')[1]}/{this.ControllerContext.RouteData.Values["controller"].ToString()}/images/image {date}.mobile.jpg";

                return View($"{date}");
            }
            else
            {
                ViewData["BaseUrl"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}{this.Request.Path}";
                ViewData["Title"] = _localizer[$"title"];
                ViewData["Image"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}/{this.Request.Path.ToString().Split('/')[1]}/{this.ControllerContext.RouteData.Values["controller"].ToString()}/images/index.jpg";
            }

            return View();
        }
    }
}

Calendar/Controllers/OctoberController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Calendar.Models;
using Microsoft.Extensions.Localization;

namespace Calendar.Controllers
{
    public class OctoberController : Controller
    {
        private readonly IStringLocalizer<OctoberController> _localizer;

        public OctoberController(IStringLocalizer<OctoberController> localizer)
        {
            _localizer = localizer;
        }

        public IActionResult Index(int date)
        {
            ViewData["Url"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}{this.Request.Path}{this.Request.QueryString}";

            if (date > 0)
            {
                ViewData["BaseUrl"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}/{this.Request.Path.ToString().Split('/')[1]}/{this.ControllerContext.RouteData.Values["controller"].ToString()}";
                ViewData["Title"] = _localizer[$"{date}title"];
                ViewData["Description"] = _localizer[$"{date}description"];
                ViewData["Image"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}/{this.Request.Path.ToString().Split('/')[1]}/{this.ControllerContext.RouteData.Values["controller"].ToString()}/images/image {date}.mobile.jpg";

                return View($"{date}");
            }
            else
            {
                ViewData["BaseUrl"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}{this.Request.Path}";
                ViewData["Title"] = _localizer[$"title"];
                ViewData["Image"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}/{this.Request.Path.ToString().Split('/')[1]}/{this.ControllerContext.RouteData.Values["controller"].ToString()}/images/index.jpg";
            }

            return View();
        }
    }
}

Calendar/Controllers/SeptemberController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Calendar.Models;
using Microsoft.Extensions.Localization;

namespace Calendar.Controllers
{
    public class SeptemberController : Controller
    {
        private readonly IStringLocalizer<SeptemberController> _localizer;

        public SeptemberController(IStringLocalizer<SeptemberController> localizer)
        {
            _localizer = localizer;
        }

        public IActionResult Index(int date)
        {
            ViewData["Url"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}{this.Request.Path}{this.Request.QueryString}";

            if (date > 0)
            {
                ViewData["BaseUrl"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}/{this.Request.Path.ToString().Split('/')[1]}/{this.ControllerContext.RouteData.Values["controller"].ToString()}";
                ViewData["Title"] = _localizer[$"{date}title"];
                ViewData["Description"] = _localizer[$"{date}description"];
                ViewData["Image"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}/{this.Request.Path.ToString().Split('/')[1]}/{this.ControllerContext.RouteData.Values["controller"].ToString()}/images/image {date}.mobile.jpg";

                return View($"{date}");
            }
            else
            {
                ViewData["BaseUrl"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}{this.Request.Path}";
                ViewData["Title"] = _localizer[$"title"];
                ViewData["Image"] = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}/{this.Request.Path.ToString().Split('/')[1]}/{this.ControllerContext.RouteData.Values["controller"].ToString()}/images/index.jpg";
            }

            return View();
        }
    }
}

Calendar/Views/October/16.cshtml
@{
    Layout = null;

    string CurrentUrl = ViewData["Url"].ToString();
    string BaseUrl = ViewData["BaseUrl"].ToString();
    string ImageUrl = ViewData["Image"].ToString();
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/images/logo/set.svg">

    <link rel=”canonical” href="@CurrentUrl" />
    <meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
    <meta name="description" content="@ViewData["Description"]">

    <meta property="og:url" content="@CurrentUrl" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="@ViewData["Title"]" />
    <meta property="og:description" content="@ViewData["Description"]" />
    <meta property="og:image" content="@ImageUrl" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site.month.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body style="">
    <header>
        <nav>
            <div class="">
                <div class="d-flex header-nav">
                    <div class="mr-auto p-2">
                        <img src="~/images/logo/set.svg" class="logo-set" />
                    </div>
                    <div class="p-2 div-setmarkeitwork">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="~/images/shared/home.svg" class="logo-home" />
                        </a>
                        <a data-toggle="modal" data-target="#menu">
                            <img src="~/images/shared/menu.svg" class="logo-menu" />
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            <partial name="content" />

            <script>
                var x = window.matchMedia("(max-width: 1100px)");
                x.addListener(openDialog(x));

                function openDialog(x) {
                    if (x.matches) {
                        $('#dialogmobile16').modal('show');
                    } else {
                        $('#dialog16').modal('show');
                    }
                }

                $(document).ready(function () {
                    openDialog(x);
                });
            </script>
        </main>
    </div>

    <section>
        <div class="modal fade hide" id="menu" tabindexdialog="-1" aria-hidden="true" data-backdrop="true">
            <div class="modal-dialog modal-dialog-centered custom-size-dialog-sharesocial" style="overflow-y:hidden">
                <div class="modal-content">
                    <a class="btn-close" data-dismiss="modal" aria-label="Close">
                        <img src="~/images/shared/button-close-black.svg" style="width:4vw;max-width: 30px;" />
                    </a>
                    <div class="share-panel-dialog-sharesocial">
                        @await Html.PartialAsync("~/Views/Shared/ShareSocialMedia.cshtml", new ShareDialogModels() { Url = BaseUrl })
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

Calendar/Views/October/21.cshtml
@{
    Layout = null;

    string CurrentUrl = ViewData["Url"].ToString();
    string BaseUrl = ViewData["BaseUrl"].ToString();
    string ImageUrl = ViewData["Image"].ToString();
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/images/logo/set.svg">

    <link rel=”canonical” href="@CurrentUrl" />
    <meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
    <meta name="description" content="@ViewData["Description"]">

    <meta property="og:url" content="@CurrentUrl" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="@ViewData["Title"]" />
    <meta property="og:description" content="@ViewData["Description"]" />
    <meta property="og:image" content="@ImageUrl" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site.month.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body style="">
    <header>
        <nav>
            <div class="">
                <div class="d-flex header-nav">
                    <div class="mr-auto p-2">
                        <img src="~/images/logo/set.svg" class="logo-set" />
                    </div>
                    <div class="p-2 div-setmarkeitwork">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="~/images/shared/home.svg" class="logo-home" />
                        </a>
                        <a data-toggle="modal" data-target="#menu">
                            <img src="~/images/shared/menu.svg" class="logo-menu" />
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            <partial name="content" />

            <script>
                var x = window.matchMedia("(max-width: 1100px)");
                x.addListener(openDialog(x));

                function openDialog(x) {
                    if (x.matches) {
                        $('#dialogmobile21').modal('show');
                    } else {
                        $('#dialog21').modal('show');
                    }
                }

                $(document).ready(function () {
                    openDialog(x);
                });
            </script>
        </main>
    </div>

    <section>
        <div class="modal fade hide" id="menu" tabindexdialog="-1" aria-hidden="true" data-backdrop="true">
            <div class="modal-dialog modal-dialog-centered custom-size-dialog-sharesocial" style="overflow-y:hidden">
                <div class="modal-content">
                    <a class="btn-close" data-dismiss="modal" aria-label="Close">
                        <img src="~/images/shared/button-close-black.svg" style="width:4vw;max-width: 30px;" />
                    </a>
                    <div class="share-panel-dialog-sharesocial">
                        @await Html.PartialAsync("~/Views/Shared/ShareSocialMedia.cshtml", new ShareDialogModels() { Url = BaseUrl })
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

Calendar/Views/October/4.cshtml
@{
    Layout = null;

    string CurrentUrl = ViewData["Url"].ToString();
    string BaseUrl = ViewData["BaseUrl"].ToString();
    string ImageUrl = ViewData["Image"].ToString();
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/images/logo/set.svg">

    <link rel=”canonical” href="@CurrentUrl" />
    <meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
    <meta name="description" content="@ViewData["Description"]">

    <meta property="og:url" content="@CurrentUrl" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="@ViewData["Title"]" />
    <meta property="og:description" content="@ViewData["Description"]" />
    <meta property="og:image" content="@ImageUrl" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site.month.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body style="">
    <header>
        <nav>
            <div class="">
                <div class="d-flex header-nav">
                    <div class="mr-auto p-2">
                        <img src="~/images/logo/set.svg" class="logo-set" />
                    </div>
                    <div class="p-2 div-setmarkeitwork">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="~/images/shared/home.svg" class="logo-home" />
                        </a>
                        <a data-toggle="modal" data-target="#menu">
                            <img src="~/images/shared/menu.svg" class="logo-menu" />
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            <partial name="content" />

            <script>
                var x = window.matchMedia("(max-width: 1100px)");
                x.addListener(openDialog(x));

                function openDialog(x) {
                    if (x.matches) {
                        $('#dialogmobile4').modal('show');
                    } else {
                        $('#dialog4').modal('show');
                    }
                }

                $(document).ready(function () {
                    openDialog(x);
                });
            </script>
        </main>
    </div>

    <section>
        <div class="modal fade hide" id="menu" tabindexdialog="-1" aria-hidden="true" data-backdrop="true">
            <div class="modal-dialog modal-dialog-centered custom-size-dialog-sharesocial" style="overflow-y:hidden">
                <div class="modal-content">
                    <a class="btn-close" data-dismiss="modal" aria-label="Close">
                        <img src="~/images/shared/button-close-black.svg" style="width:4vw;max-width: 30px;" />
                    </a>
                    <div class="share-panel-dialog-sharesocial">
                        @await Html.PartialAsync("~/Views/Shared/ShareSocialMedia.cshtml", new ShareDialogModels() { Url = BaseUrl })
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

Calendar/Views/October/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.Month.cshtml";
}

<partial name="content" />

Calendar/Views/October/content.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@{
    Layout = null;
    ShareDialogModels shareDialogModels = new ShareDialogModels();
    string CurrentUrl = ViewData["Url"].ToString();
    string BaseUrl = ViewData["BaseUrl"].ToString();
}

<section class="nav-dialog desktop" id="navdialog">
    <div class="button-dialog-left" style="@Localizer["16style"]">
        <div class="row">
            <div class="column">
                <a data-toggle="modal" data-target="@("#dialog"+16)">
                    <img src="~/images/shared/circle.svg" />
                </a>
            </div>
            <div class="column">
                <p class="header-text-orange">@Localizer["16header"]</p>
                <p class="text-black">@Localizer["16text"]</p>
            </div>
        </div>
    </div>
    <div class="button-dialog-left" style="top: 61vh; left: 25%;">
        <div class="row">
            <div class="column">
                <a data-toggle="modal" data-target="@("#dialog"+4)">
                    <img src="~/images/shared/circle.svg" />
                </a>
            </div>
            <div class="column">
                <p class="header-text-orange">@Localizer["4header"]</p>
                <p class="text-black">@Localizer["4text"]</p>
            </div>
        </div>
    </div>
    <div class="button-dialog-left" style="@Localizer["21style"]">
        <div class="row">
            <div class="column">
                <a data-toggle="modal" data-target="@("#dialog"+21)">
                    <img src="~/images/shared/circle.svg" />
                </a>
            </div>
            <div class="column">
                <p class="header-text-orange">@Localizer["21header"]</p>
                <p class="text-black">@Localizer["21text"]</p>
                <p class="text-black">@Localizer["21text1"]</p>
            </div>
        </div>
    </div>
</section>

<section class="image-calendar desktop" id="cover" onload="javascript: coverLoaded();" style="background-image: url('@BaseUrl/images/index.jpg');background-repeat: no-repeat;background-size: cover;background-position: center center;height: 100vh;width: 100%">
</section>
<section class="image-calendar mobile">
    <img src="@BaseUrl/images/index.mobile.jpg" style="width: 100%" />
</section>

<section class="pagination desktop">
    <div class="div-pagination" style="bottom: 6vh;right: 18%;">
        <a class="pagination-left" href="@Url.Action("Index", "September")">
            <img src="~/images/shared/pagination-left-orange.svg" />
        </a>
        <a class="pagination-right" href="@Url.Action("Index", "November")">
            <img src="~/images/shared/pagination-right-orange.svg" />
        </a>
    </div>
</section>

<section class="pagination container mobile">
    <div class="div-pagination" style="bottom: 2vh;justify-content: space-between;width: 87vw;margin-left: -3vw;">
        <a class="pagination-left-mobile" href="@Url.Action("Index", "September")">
            <img src="~/images/shared/backwhite.mobile.svg" />
        </a>
        <a class="pagination-right-mobile" href="@Url.Action("Index", "November")">
            <img src="~/images/shared/nextwhite.mobile.svg" />
        </a>
    </div>
</section>

<section class="nav-dialog mobile" id="navdialog">
    <div>
        <div class="row">
            <div class="column-image">
                <a data-toggle="modal" data-target="@("#dialogmobile"+4)">
                    <img src="@BaseUrl/images/image 04.mobile.jpg" />
                </a>
            </div>
            <div class="column-text">
                <div class="verticlecenter">
                    <p class="header-text-orange">@Localizer["4header"]</p>
                    <p class="text-black">@Localizer["4text"]</p>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div class="row">
            <div class="column-image">
                <a data-toggle="modal" data-target="@("#dialogmobile"+16)">
                    <img src="@BaseUrl/images/image 16.mobile.jpg" />
                </a>
            </div>
            <div class="column-text">
                <div class="verticlecenter">
                    <p class="header-text-orange">@Localizer["16header"]</p>
                    <p class="text-black">@Localizer["16text"]</p>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div class="row">
            <div class="column-image">
                <a data-toggle="modal" data-target="@("#dialogmobile"+21)">
                    <img src="@BaseUrl/images/image 21.mobile.jpg" />
                </a>
            </div>
            <div class="column-text">
                <div class="verticlecenter">
                    <p class="header-text-orange">@Localizer["21header"]</p>
                    <p class="text-black">@Localizer["21textmobile"]</p>
                    <p class="text-black">@Localizer["21textmobile1"]</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="desktop">
    <div class="modal fade hide" id="@("dialog" + 4)" tabindexdialog="-1" aria-hidden="true" data-backdrop="true">
        <a class="btn-close" data-dismiss="modal" aria-label="Close">
            <img src="~/images/shared/button-close.svg" style="width: 4vw;max-width: 30px;" />
        </a>
        <div class="modal-dialog modal-dialog-centered custom-size-dialog">
            <div class="modal-content">
                <div class="infograpic">
                    <img src="@BaseUrl/images/image 04.jpg" class="infographic-image" loading="lazy" />
                </div>
                <div class="share-panel-dialog">
                    @await Html.PartialAsync("~/Views/Shared/ShareSocialMedia.Dialog.cshtml", new ShareDialogModels() { Url = $"{BaseUrl}?date={4}" })
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade hide" id="@("dialog" + 16)" tabindexdialog="-1" aria-hidden="true" data-backdrop="true">
        <a class="btn-close" data-dismiss="modal" aria-label="Close">
            <img src="~/images/shared/button-close.svg" style="width: 4vw;max-width: 30px;" />
        </a>
        <div class="modal-dialog modal-dialog-centered custom-size-dialog">
            <div class="modal-content">
                <div class="infograpic">
                    <img src="@BaseUrl/images/image 16.jpg" class="infographic-image" loading="lazy" />
                </div>
                <div class="share-panel-dialog">
                    @await Html.PartialAsync("~/Views/Shared/ShareSocialMedia.Dialog.cshtml", new ShareDialogModels() { Url = $"{BaseUrl}?date={16}" })
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade hide" id="@("dialog" + 21)" tabindexdialog="-1" aria-hidden="true" data-backdrop="true">
        <a class="btn-close" data-dismiss="modal" aria-label="Close">
            <img src="~/images/shared/button-close.svg" style="width: 4vw;max-width: 30px;" />
        </a>
        <div class="modal-dialog modal-dialog-centered custom-size-dialog">
            <div class="modal-content">
                <div class="infograpic">
                    <img src="@BaseUrl/images/image 21.jpg" class="infographic-image" loading="lazy" />
                </div>
                <div class="share-panel-dialog">
                    @await Html.PartialAsync("~/Views/Shared/ShareSocialMedia.Dialog.cshtml", new ShareDialogModels() { Url = $"{BaseUrl}?date={21}" })
                </div>
            </div>
        </div>
    </div>
</section>

<section class="mobile">
    <div class="modal fade hide" id="@("dialogmobile" + 4)" tabindexdialog="-1" aria-hidden="true" data-backdrop="true">
        <a class="btn-close" data-dismiss="modal" aria-label="Close">
            <img src="~/images/shared/button-close.svg" style="width: 4vw;max-width: 30px;" />
        </a>
        <div class="modal-dialog custom-size-dialog">
            <div class="modal-content modal-black">
                <div class="infograpic">
                    <img src="@BaseUrl/images/image 04.jpg" class="infographic-image" loading="lazy" />
                    <div class="share-panel-dialog">
                        @await Html.PartialAsync("~/Views/Shared/ShareSocialMedia.Dialog.mobile.cshtml", new ShareDialogModels() { Url = $"{BaseUrl}?date={4}" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade hide" id="@("dialogmobile" + 16)" tabindexdialog="-1" aria-hidden="true" data-backdrop="true">
        <a class="btn-close" data-dismiss="modal" aria-label="Close">
            <img src="~/images/shared/button-close.svg" style="width: 4vw;max-width: 30px;" />
        </a>
        <div class="modal-dialog custom-size-dialog">
            <div class="modal-content modal-black">
                <div class="infograpic">
                    <img src="@BaseUrl/images/image 16.jpg" class="infographic-image" loading="lazy" />
                    <div class="share-panel-dialog">
                        @await Html.PartialAsync("~/Views/Shared/ShareSocialMedia.Dialog.mobile.cshtml", new ShareDialogModels() { Url = $"{BaseUrl}?date={16}" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade hide" id="@("dialogmobile" + 21)" tabindexdialog="-1" aria-hidden="true" data-backdrop="true">
        <a class="btn-close" data-dismiss="modal" aria-label="Close">
            <img src="~/images/shared/button-close.svg" style="width: 4vw;max-width: 30px;" />
        </a>
        <div class="modal-dialog custom-size-dialog">
            <div class="modal-content modal-black">
                <div class="infograpic">
                    <img src="@BaseUrl/images/image 21.jpg" class="infographic-image" loading="lazy" />
                    <div class="share-panel-dialog">
                        @await Html.PartialAsync("~/Views/Shared/ShareSocialMedia.Dialog.mobile.cshtml", new ShareDialogModels() { Url = $"{BaseUrl}?date={16}" })
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>